### ISSUE TITLE
Offline ServiceWorker only works in https context.

### ISSUE THREAD

**Issue by ghoullier** [ldiringer/bcagenda#2]
ServiceWorker only works in https context.

```console
ServiceWorker registration failed:  DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
```

Can your support https for bca.tanisca.com?

**Comment by ldiringer** [comment]
Yep, there is a HTTPS version at https://bca.tanisca.com
The HTTP version still exist for people having their agenda in the HTTP localstorage.
However, the HTTP version now has a warning message on top of the homepage to encourage users to use the HTTPS version.

**Comment by ghoullier** [comment]
The application seems to be not correctly deployed in https context...

<img width="722" alt="capture d ecran 2017-04-14 a 09 46 47" src="https://cloud.githubusercontent.com/assets/2315749/25037075/612a492a-20f7-11e7-999d-22371fc9399c.png">

[service-worker.js](https://bca.tanisca.com/service-worker.js) respond with 404 http code.

**Comment by ldiringer** [comment]
This file is now deployed.
`ServiceWorker registration successful with scope:  https://bca.tanisca.com/`
